version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/package"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
    automerge: true
    automerge-type: "pr"
    groups:
      react-and-related:
        patterns:
          - "react"
          - "react-dom"
          - "@testing-library/react"
      build-tools:
        patterns:
          - "typescript"
          - "babel"
      types:
        patterns:
          - "@types/*"
      linting:
        patterns:
          - "eslint"
          - "prettier"
      testing:
        patterns:
          - "jest"
          - "@testing-library/*"
      all-other-deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/demo"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
    automerge: true
    automerge-type: "pr"
    groups:
      react-and-related:
        patterns:
          - "react"
          - "react-dom"
          - "@testing-library/react"
      build-tools:
        patterns:
          - "typescript"
          - "next"
      types:
        patterns:
          - "@types/*"
      linting:
        patterns:
          - "eslint"
          - "prettier"
      testing:
        patterns:
          - "jest"
          - "@testing-library/*"
      all-other-deps:
        patterns:
          - "*"
